# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_contracts/group_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpc_contracts/group_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"grpc_contracts/group_service.proto\x12\x13groupsapp.groups.v1\";\n\x16\x43heckMembershipRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\":\n\x17\x43heckMembershipResponse\x12\x11\n\tis_member\x18\x01 \x01(\x08\x12\x0c\n\x04role\x18\x02 \x01(\t2\x84\x01\n\x14GroupInternalService\x12l\n\x0f\x43heckMembership\x12+.groupsapp.groups.v1.CheckMembershipRequest\x1a,.groupsapp.groups.v1.CheckMembershipResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_contracts.group_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKMEMBERSHIPREQUEST']._serialized_start=59
  _globals['_CHECKMEMBERSHIPREQUEST']._serialized_end=118
  _globals['_CHECKMEMBERSHIPRESPONSE']._serialized_start=120
  _globals['_CHECKMEMBERSHIPRESPONSE']._serialized_end=178
  _globals['_GROUPINTERNALSERVICE']._serialized_start=181
  _globals['_GROUPINTERNALSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
